// <auto-generated />
using BlazorEcommerce.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorEcommerce.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlazorEcommerce.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "With more than 20% of affiliate marketers each making over $50,000 a year, and well over half of those in the six figure bracket, the upside potential for a nice annual income looks quite promising for anyone who is looking for a new source of revenue.",
                            ImageUrl = "https://www.ebookjunkie.com/sites/default/files/ebook_images/affiliate_marketing_plan_profit_bundle.jpg",
                            Price = 9.99m,
                            Title = "Affiliate Marketing Plan"
                        },
                        new
                        {
                            Id = 2,
                            Description = "With more than 205 billion emails being sent and received every day if your business isn't taking advantage of this powerful and massive marketing channel, then you are missing out on a highly effective way to reach your target audience.",
                            ImageUrl = "https://www.ebookjunkie.com/sites/default/files/ebook_images/email_marketing_success2.jpg",
                            Price = 5.99m,
                            Title = "Email Marketing Success"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Being a solopreneur means being an entrepreneur that runs everything themselves. There are countless advantages to this kind of business model, and thanks to the web, it's now more feasible for more people than ever before.",
                            ImageUrl = "https://www.ebookjunkie.com/sites/default/files/ebook_images/productive_solopreneur_0.jpg",
                            Price = 7.99m,
                            Title = "The Productive Solopreneur"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
